### PR TITLE
Speed ups and waits for buffer to empty on quit

### PR DESCRIPTION
**Pull request by lawrenceleejr**
* Cuts per-packet processing time by about a factor of 2. 
* On break, this now waits for the buffer to clear.

As far as I can tell, this can handle about 15kHz in input, and on my laptop (2 cores) about 10 kHz in output. The output rate should be increasable with more cores. Input rate limited by the python. Could use some optimization or can `Cythonize` or `ctypes`-ize.

### CODE REVIEW

**Comment by alexandertuna** [comment]
Love it. @sezata can you take a look and merge at your leisure?

I think I have a fix for https://github.com/sezata/trigger_daq/issues/25, I'll test and PR with this update.

**Comment by alexandertuna** [comment]
Update: `python udpReceive_32bit_MP.py -h` crashes for me.

**Comment by alexandertuna** [comment]
Eh, I had trouble with the fix, I vote for just merging this ONCE THE -H OPTION WORKS

**Comment by lawrenceleejr** [comment]
Did it work after #24?

**Comment by lawrenceleejr** [comment]
fixed now. also made it executable.

**Comment by sezata** [comment]
Hi Larry,

will test today- there's been no beam the past few days! :(

**Pull request merged**
